#include "ShuffleRocks.h"
#include "soh_assets.h"
#include "static_data.h"

extern "C" {
#include "variables.h"
#include "overlays/actors/ovl_En_Ishi/z_en_ishi.h"
#include "overlays/actors/ovl_Obj_Bombiwa/z_obj_bombiwa.h"
#include "overlays/actors/ovl_Obj_Hamishi/z_obj_hamishi.h"
#include "objects/gameplay_field_keep/gameplay_field_keep.h"
#include "objects/object_bombiwa/object_bombiwa.h"
extern PlayState* gPlayState;
}

#define RAND_GET_OPTION(option) Rando::Context::GetInstance()->GetOption(option).Get()

extern void EnItem00_DrawRandomizedItem(EnItem00* enItem00, PlayState* play);

extern "C" void EnIshi_RandomizerDraw(Actor* thisx, PlayState* play) {
    auto rockActor = ((EnIshi*)thisx);

    OPEN_DISPS(play->state.gfxCtx);
    Gfx_SetupDL_25Opa(play->state.gfxCtx);
    gDPSetGrayscaleColor(POLY_OPA_DISP++, 175, 255, 0, 255);

    if (rockActor->rockIdentity.randomizerCheck != RC_MAX &&
        Flags_GetRandomizerInf(rockActor->rockIdentity.randomizerInf) == 0) {
        gSPGrayscale(POLY_OPA_DISP++, true);
    }

    if (rockActor->actor.params & 1) {
        Gfx_SetupDL_25Opa(play->state.gfxCtx);
        gSPMatrix(POLY_OPA_DISP++, MATRIX_NEWMTX(play->state.gfxCtx),
                  G_MTX_NOPUSH | G_MTX_LOAD | G_MTX_MODELVIEW);
        gDPSetPrimColor(POLY_OPA_DISP++, 0, 0, 255, 255, 255, 255);
        gSPDisplayList(POLY_OPA_DISP++, (Gfx*)gSilverRockDL);
    } else {
        Gfx_DrawDListOpa(play, (Gfx*)gFieldKakeraDL);
    }

    gSPGrayscale(POLY_OPA_DISP++, false);

    CLOSE_DISPS(play->state.gfxCtx);
}

extern "C" void ObjBombiwa_RandomizerDraw(Actor* thisx, PlayState* play) {
    auto rockActor = ((ObjBombiwa*)thisx);

    OPEN_DISPS(play->state.gfxCtx);
    Gfx_SetupDL_25Opa(play->state.gfxCtx);
    gDPSetGrayscaleColor(POLY_OPA_DISP++, 175, 255, 0, 255);

    if (rockActor->rockIdentity.randomizerCheck != RC_MAX &&
        Flags_GetRandomizerInf(rockActor->rockIdentity.randomizerInf) == 0) {
        gSPGrayscale(POLY_OPA_DISP++, true);
    }

    Gfx_DrawDListOpa(play, (Gfx*)object_bombiwa_DL_0009E0);

    gSPGrayscale(POLY_OPA_DISP++, false);

    CLOSE_DISPS(play->state.gfxCtx);
}

extern "C" void ObjHamishi_RandomizerDraw(Actor* thisx, PlayState* play) {
    auto rockActor = ((ObjHamishi*)thisx);

    OPEN_DISPS(play->state.gfxCtx);
    Gfx_SetupDL_25Opa(play->state.gfxCtx);
    gDPSetGrayscaleColor(POLY_OPA_DISP++, 175, 255, 0, 255);

    if (rockActor->rockIdentity.randomizerCheck != RC_MAX &&
        Flags_GetRandomizerInf(rockActor->rockIdentity.randomizerInf) == 0) {
        gSPGrayscale(POLY_OPA_DISP++, true);
    }

    Gfx_SetupDL_25Opa(play->state.gfxCtx);

    gSPMatrix(POLY_OPA_DISP++, MATRIX_NEWMTX(play->state.gfxCtx),
              G_MTX_NOPUSH | G_MTX_LOAD | G_MTX_MODELVIEW);
    gDPSetPrimColor(POLY_OPA_DISP++, 0, 0, 255, 170, 130, 255);
    gSPDisplayList(POLY_OPA_DISP++, (Gfx*)gSilverRockDL);

    gSPGrayscale(POLY_OPA_DISP++, false);

    CLOSE_DISPS(play->state.gfxCtx);
}

uint8_t Rock_RandomizerHoldsItem(RockIdentity rockIdentity, PlayState* play) {
    RandomizerCheck rc = rockIdentity.randomizerCheck;
    if (rc == RC_MAX)
        return false;

    uint8_t rockSetting = Rando::Context::GetInstance()->GetOption(RSK_SHUFFLE_ROCKS).Get();

    // Don't pull randomized item if rock isn't randomized or is already checked
    return IS_RANDO && rockSetting &&
        !Flags_GetRandomizerInf(rockIdentity.randomizerInf) &&
        rockIdentity.randomizerCheck != RC_UNKNOWN_CHECK;
}

void Rock_RandomizerSpawnCollectible(Actor* actor, RockIdentity rockIdentity, PlayState* play) {
    LUSLOG_INFO("ROCKdrop %d\t:\t%d, %d", rockIdentity.randomizerCheck, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    EnItem00* item00 = (EnItem00*)Item_DropCollectible2(play, &actor->world.pos, ITEM00_SOH_DUMMY);
    item00->randoInf = rockIdentity.randomizerInf;
    item00->itemEntry = Rando::Context::GetInstance()->GetFinalGIEntry(rockIdentity.randomizerCheck, true, GI_NONE);
    item00->actor.draw = (ActorFunc)EnItem00_DrawRandomizedItem;
    item00->actor.velocity.y = 9.0f;
    item00->actor.speedXZ = 2.0f;
    item00->actor.world.rot.y = Rand_CenteredFloat(65536.0f);
}

void EnIshi_RandomizerInit(void* actorRef) {
    Actor* actor = static_cast<Actor*>(actorRef);

    if (actor->id != ACTOR_EN_ISHI)
        return;

    EnIshi* rockActor = static_cast<EnIshi*>(actorRef);

    rockActor->rockIdentity = OTRGlobals::Instance->gRandomizer->IdentifyRock(
        gPlayState->sceneNum, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    if (rockActor->rockIdentity.randomizerCheck == RC_MAX) {
        LUSLOG_WARN("ROCK ishi  %d\t:\t%d, %d", rockActor->rockIdentity.randomizerCheck, actor->params&1, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    } else {
        LUSLOG_INFO("ROCK ishi%d %d\t:\t%d, %d", rockActor->rockIdentity.randomizerCheck, actor->params&1, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    }

    if (Rock_RandomizerHoldsItem(rockActor->rockIdentity, gPlayState)) {
        rockActor->actor.draw = EnIshi_RandomizerDraw;
    }
}

void ObjBombiwa_RandomizerInit(void* actorRef) {
    Actor* actor = static_cast<Actor*>(actorRef);

    if (actor->id != ACTOR_OBJ_BOMBIWA)
        return;

    ObjBombiwa* rockActor = static_cast<ObjBombiwa*>(actorRef);

    rockActor->rockIdentity = OTRGlobals::Instance->gRandomizer->IdentifyRock(
        gPlayState->sceneNum, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    if (rockActor->rockIdentity.randomizerCheck == RC_MAX) {
        LUSLOG_INFO("ROCK bombiwa\t:\t%d, %d", rockActor->rockIdentity.randomizerCheck, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    } else {
        LUSLOG_INFO("ROCK bombiwa%d\t:\t%d, %d", rockActor->rockIdentity.randomizerCheck, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    }
    if (Rock_RandomizerHoldsItem(rockActor->rockIdentity, gPlayState)) {
        rockActor->actor.draw = ObjBombiwa_RandomizerDraw;
    }
}

void ObjHamishi_RandomizerInit(void* actorRef) {
    Actor* actor = static_cast<Actor*>(actorRef);

    if (actor->id != ACTOR_OBJ_HAMISHI)
        return;

    ObjHamishi* rockActor = static_cast<ObjHamishi*>(actorRef);

    rockActor->rockIdentity = OTRGlobals::Instance->gRandomizer->IdentifyRock(
        gPlayState->sceneNum, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    if (rockActor->rockIdentity.randomizerCheck == RC_MAX) {
        LUSLOG_WARN("ROCK hamishi\t:\t%d, %d", rockActor->rockIdentity.randomizerCheck, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    } else {
        LUSLOG_INFO("ROCK hamishi%d\t:\t%d, %d", rockActor->rockIdentity.randomizerCheck, (s16)actor->world.pos.x, (s16)actor->world.pos.z);
    }
    if (Rock_RandomizerHoldsItem(rockActor->rockIdentity, gPlayState)) {
        rockActor->actor.draw = ObjHamishi_RandomizerDraw;
    }
}

void ObjBombiwa_RandomizerKill(void* actorRef) {
    Actor* actor = static_cast<Actor*>(actorRef);

    if (actor->id != ACTOR_OBJ_BOMBIWA)
        return;

    ObjBombiwa* rockActor = static_cast<ObjBombiwa*>(actorRef);

    if (Rock_RandomizerHoldsItem(rockActor->rockIdentity, gPlayState)) {
        Rock_RandomizerSpawnCollectible(&rockActor->actor, rockActor->rockIdentity, gPlayState);
        rockActor->rockIdentity.randomizerCheck = RC_MAX;
        rockActor->rockIdentity.randomizerInf = RAND_INF_MAX;
    }
}

void ObjHamishi_RandomizerKill(void* actorRef) {
    Actor* actor = static_cast<Actor*>(actorRef);

    if (actor->id != ACTOR_OBJ_HAMISHI)
        return;

    ObjHamishi* rockActor = static_cast<ObjHamishi*>(actorRef);

    if (Rock_RandomizerHoldsItem(rockActor->rockIdentity, gPlayState)) {
        Rock_RandomizerSpawnCollectible(&rockActor->actor, rockActor->rockIdentity, gPlayState);
        rockActor->rockIdentity.randomizerCheck = RC_MAX;
        rockActor->rockIdentity.randomizerInf = RAND_INF_MAX;
    }
}

void RegisterShuffleRock() {
    bool shouldRegister = IS_RANDO && RAND_GET_OPTION(RSK_SHUFFLE_ROCKS);

    COND_ID_HOOK(OnActorInit, ACTOR_EN_ISHI, shouldRegister, EnIshi_RandomizerInit);
    COND_ID_HOOK(OnActorInit, ACTOR_OBJ_BOMBIWA, shouldRegister, ObjBombiwa_RandomizerInit);
    COND_ID_HOOK(OnActorInit, ACTOR_OBJ_HAMISHI, shouldRegister, ObjHamishi_RandomizerInit);
    COND_ID_HOOK(OnActorKill, ACTOR_OBJ_BOMBIWA, shouldRegister, ObjBombiwa_RandomizerKill);
    COND_ID_HOOK(OnActorKill, ACTOR_OBJ_HAMISHI, shouldRegister, ObjHamishi_RandomizerKill);

    COND_VB_SHOULD(VB_ROCK_DROP_ITEM, shouldRegister, {
        EnIshi* rockActor = va_arg(args, EnIshi*);
        if (Rock_RandomizerHoldsItem(rockActor->rockIdentity, gPlayState)) {
            Rock_RandomizerSpawnCollectible(&rockActor->actor, rockActor->rockIdentity, gPlayState);
            rockActor->rockIdentity.randomizerCheck = RC_MAX;
            rockActor->rockIdentity.randomizerInf = RAND_INF_MAX;
            *should = false;
        }
    });

    COND_VB_SHOULD(VB_BOULDER_BREAK_FLAG, shouldRegister, {
        ObjBombiwa* rockActor = va_arg(args, ObjBombiwa*);
        auto rockIdentity = OTRGlobals::Instance->gRandomizer->IdentifyRock(
            gPlayState->sceneNum, (s16)rockActor->actor.world.pos.x, (s16)rockActor->actor.world.pos.z);
        if (Rock_RandomizerHoldsItem(rockIdentity, gPlayState)) {
            Flags_UnsetSwitch(gPlayState, rockActor->actor.params & 0x3F);
            *should = false;
        }
    });

    COND_VB_SHOULD(VB_BRONZE_BOULDER_BREAK_FLAG, shouldRegister, {
        ObjHamishi* rockActor = va_arg(args, ObjHamishi*);
        auto rockIdentity = OTRGlobals::Instance->gRandomizer->IdentifyRock(
            gPlayState->sceneNum, (s16)rockActor->actor.world.pos.x, (s16)rockActor->actor.world.pos.z);
        if (Rock_RandomizerHoldsItem(rockIdentity, gPlayState)) {
            Flags_UnsetSwitch(gPlayState, rockActor->actor.params & 0x3F);
            *should = false;
        }
    });
}

static RegisterShipInitFunc initFunc(RegisterShuffleRock, { "IS_RANDO" });

void Rando::StaticData::RegisterRockLocations() {
#define ROCKLOC(id, area, scene, x, z) (locationTable[RC_##id] = Location::Rock(RC_##id, RCQUEST_BOTH, area, scene, TWO_ACTOR_PARAMS(x, z), #id, #id, RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_##id)))
    ROCKLOC(KF_CIRCLE_ROCK_1, RCAREA_KOKIRI_FOREST, SCENE_KOKIRI_FOREST, -292, -350);
    ROCKLOC(KF_CIRCLE_ROCK_2, RCAREA_KOKIRI_FOREST, SCENE_KOKIRI_FOREST, -235, -373);
    ROCKLOC(KF_CIRCLE_ROCK_3, RCAREA_KOKIRI_FOREST, SCENE_KOKIRI_FOREST, -212, -430);
    ROCKLOC(KF_CIRCLE_ROCK_4, RCAREA_KOKIRI_FOREST, SCENE_KOKIRI_FOREST, -235, -486);
    ROCKLOC(KF_CIRCLE_ROCK_5, RCAREA_KOKIRI_FOREST, SCENE_KOKIRI_FOREST, -292, -510);
    ROCKLOC(KF_CIRCLE_ROCK_6, RCAREA_KOKIRI_FOREST, SCENE_KOKIRI_FOREST, -348, -486);
    ROCKLOC(KF_CIRCLE_ROCK_7, RCAREA_KOKIRI_FOREST, SCENE_KOKIRI_FOREST, -372, -430);
    ROCKLOC(KF_CIRCLE_ROCK_8, RCAREA_KOKIRI_FOREST, SCENE_KOKIRI_FOREST, -348, -373);
    ROCKLOC(KF_ROCK, RCAREA_KOKIRI_FOREST, SCENE_KOKIRI_FOREST, -672, -623);
    ROCKLOC(LW_BOULDER_1, RCAREA_LOST_WOODS, SCENE_LOST_WOODS, 670, -2520);
    ROCKLOC(LW_BOULDER_2, RCAREA_LOST_WOODS, SCENE_LOST_WOODS, 915,-925);
    ROCKLOC(LW_RUPEE_BOULDER, RCAREA_LOST_WOODS, SCENE_LOST_WOODS, 1720, -2510);

    locationTable[RC_HC_ROCK_1] = Location::Rock(RC_HC_ROCK_1, RCQUEST_BOTH, RCAREA_HYRULE_CASTLE, SCENE_HYRULE_CASTLE, TWO_ACTOR_PARAMS(-216, 2977), "HC Rock 1", "HC Rock 1",  RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_HC_ROCK_1));
    locationTable[RC_HC_ROCK_2] = Location::Rock(RC_HC_ROCK_2, RCQUEST_BOTH, RCAREA_HYRULE_CASTLE, SCENE_HYRULE_CASTLE, TWO_ACTOR_PARAMS(-110, 3006), "HC Rock 2", "HC Rock 2",  RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_HC_ROCK_2));
    locationTable[RC_HC_ROCK_3] = Location::Rock(RC_HC_ROCK_3, RCQUEST_BOTH, RCAREA_HYRULE_CASTLE, SCENE_HYRULE_CASTLE, TWO_ACTOR_PARAMS(-129, 2897), "HC Rock 3", "HC Rock 3",  RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_HC_ROCK_3));
    ROCKLOC(HC_BOULDER, RCAREA_HYRULE_CASTLE, SCENE_HYRULE_CASTLE, 2730, 2540);
    ROCKLOC(OGC_BRONZE_BOULDER_1,RCAREA_HYRULE_CASTLE,SCENE_OUTSIDE_GANONS_CASTLE,2324,533);
    ROCKLOC(OGC_BRONZE_BOULDER_2,RCAREA_HYRULE_CASTLE,SCENE_OUTSIDE_GANONS_CASTLE,1590,787);
    ROCKLOC(OGC_BRONZE_BOULDER_3,RCAREA_HYRULE_CASTLE,SCENE_OUTSIDE_GANONS_CASTLE,1661,748);
    ROCKLOC(OGC_SILVER_BOULDER_1,RCAREA_HYRULE_CASTLE,SCENE_OUTSIDE_GANONS_CASTLE,1606,685);
    ROCKLOC(OGC_SILVER_BOULDER_2,RCAREA_HYRULE_CASTLE,SCENE_OUTSIDE_GANONS_CASTLE,1766,726);
    ROCKLOC(OGC_SILVER_BOULDER_3,RCAREA_HYRULE_CASTLE,SCENE_OUTSIDE_GANONS_CASTLE,1701,661);
    ROCKLOC(OGC_SILVER_BOULDER_4,RCAREA_HYRULE_CASTLE,SCENE_OUTSIDE_GANONS_CASTLE,2260,560);

    ROCKLOC(DMC_ROCK_BY_FIRE_TEMPLE_1, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, -50, -714);
    ROCKLOC(DMC_ROCK_BY_FIRE_TEMPLE_2, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, -26, -807);
    ROCKLOC(DMC_ROCK_BY_FIRE_TEMPLE_3, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, 61, -763);
    ROCKLOC(DMC_ROCK_BY_FIRE_TEMPLE_4, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, 71, -610);
    ROCKLOC(DMC_ROCK_BY_FIRE_TEMPLE_5, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, 79, -700);
    ROCKLOC(DMC_CIRCLE_ROCK_1, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, 40, 1850);
    ROCKLOC(DMC_CIRCLE_ROCK_2, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, 96, 1826);
    ROCKLOC(DMC_CIRCLE_ROCK_3, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, 120, 1770);
    ROCKLOC(DMC_CIRCLE_ROCK_4, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, 96, 1713);
    ROCKLOC(DMC_CIRCLE_ROCK_5, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER,  40, 1690);
    ROCKLOC(DMC_CIRCLE_ROCK_6, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER,  -16, 1713);
    ROCKLOC(DMC_CIRCLE_ROCK_7, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER,  -40, 1770);
    ROCKLOC(DMC_CIRCLE_ROCK_8, RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER,  -16, 1826);
    ROCKLOC(DMC_BOULDER_1,RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, -504,1070);
    ROCKLOC(DMC_BOULDER_2,RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, 236,1199);
    ROCKLOC(DMC_BOULDER_3,RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, 40,1770);
    ROCKLOC(DMC_BRONZE_BOULDER_1,RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, -1699,-472);
    ROCKLOC(DMC_BRONZE_BOULDER_2,RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, -1332,921);
    ROCKLOC(DMC_BRONZE_BOULDER_3,RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, -1303,975);
    ROCKLOC(DMC_BRONZE_BOULDER_4,RCAREA_DEATH_MOUNTAIN_CRATER, SCENE_DEATH_MOUNTAIN_CRATER, -1060,944);

    ROCKLOC(GV_SILVER_BOULDER,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,280,1470);
    ROCKLOC(GV_ROCK_1,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,2738,297);
    ROCKLOC(GV_ROCK_2,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,2715,316);
    ROCKLOC(GV_ROCK_3,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,2699,275);
    ROCKLOC(GV_UNDERWATER_ROCK_1,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,1559,-63);
    ROCKLOC(GV_UNDERWATER_ROCK_2,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,1605,26);
    ROCKLOC(GV_UNDERWATER_ROCK_3,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,1686,-33);
    ROCKLOC(GV_ROCK_ACROSS_BRIDGE_1,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-666,-899);
    ROCKLOC(GV_ROCK_ACROSS_BRIDGE_2,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-526,-890);
    ROCKLOC(GV_ROCK_ACROSS_BRIDGE_3,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-607,-791);
    ROCKLOC(GV_ROCK_ACROSS_BRIDGE_4,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-458,-782);
    ROCKLOC(GV_BOULDER_1,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,751, 569);
    ROCKLOC(GV_BOULDER_2,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,545, -510);
    ROCKLOC(GV_BOULDER_ACROSS_BRIDGE,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-954, 577);
    ROCKLOC(GV_BRONZE_BOULDER_1,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,861, -778  );
    ROCKLOC(GV_BRONZE_BOULDER_2,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,735, 375   );
    ROCKLOC(GV_BRONZE_BOULDER_ACROSS_BRIDGE_1,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-1352, 767 );
    ROCKLOC(GV_BRONZE_BOULDER_ACROSS_BRIDGE_2,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-1695, -350);
    ROCKLOC(GV_BRONZE_BOULDER_ACROSS_BRIDGE_3,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-1001, 637 );
    ROCKLOC(GV_BRONZE_BOULDER_ACROSS_BRIDGE_4,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-1291, 787 );
    ROCKLOC(GV_BRONZE_BOULDER_ACROSS_BRIDGE_5,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-1416, 778 );
    ROCKLOC(GV_BRONZE_BOULDER_ACROSS_BRIDGE_6,RCAREA_GERUDO_VALLEY,SCENE_GERUDO_VALLEY,-1256, 856 );

    ROCKLOC(HF_SILVER_BOULDER,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,674,8256);
    ROCKLOC(HF_ROCK_1,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7875,6995);
    ROCKLOC(HF_ROCK_2,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7818,6971);
    ROCKLOC(HF_ROCK_3,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7795,6915);
    ROCKLOC(HF_ROCK_4,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7818,6858);
    ROCKLOC(HF_ROCK_5,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7875,6835);
    ROCKLOC(HF_ROCK_6,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7931,6858);
    ROCKLOC(HF_ROCK_7,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7955,6915);
    ROCKLOC(HF_ROCK_8,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7931,6971);
    ROCKLOC(HF_BOULDER_1,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-4450,-425);
    ROCKLOC(HF_BOULDER_2,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-1425,810);
    ROCKLOC(HF_BOULDER_3,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-270,12350);
    ROCKLOC(HF_BRONZE_BOULDER_1,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7870,6920);
    ROCKLOC(HF_BRONZE_BOULDER_2,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-7804,7983);
    ROCKLOC(HF_BRONZE_BOULDER_3,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-8397,7947);
    ROCKLOC(HF_BRONZE_BOULDER_4,RCAREA_HYRULE_FIELD,SCENE_HYRULE_FIELD,-6461,8220);

    ROCKLOC(KAK_SILVER_BOULDER,RCAREA_KAKARIKO_VILLAGE,SCENE_KAKARIKO_VILLAGE,1436,1361);
    ROCKLOC(KAK_ROCK_1,RCAREA_KAKARIKO_VILLAGE,SCENE_KAKARIKO_VILLAGE,220,-1236);
    ROCKLOC(KAK_ROCK_2,RCAREA_KAKARIKO_VILLAGE,SCENE_KAKARIKO_VILLAGE,-664,1288);
    ROCKLOC(GY_ROCK,RCAREA_GRAVEYARD,SCENE_GRAVEYARD,-1193,693);

    ROCKLOC(LA_ROCK,RCAREA_LAKE_HYLIA, SCENE_LAKE_HYLIA,  1222, 3953);
    ROCKLOC(ZD_CIRCLE_ROCK_1, RCAREA_ZORAS_DOMAIN, SCENE_ZORAS_DOMAIN, 462, -696);
    ROCKLOC(ZD_CIRCLE_ROCK_2, RCAREA_ZORAS_DOMAIN, SCENE_ZORAS_DOMAIN, 518,-719);
    ROCKLOC(ZD_CIRCLE_ROCK_3, RCAREA_ZORAS_DOMAIN, SCENE_ZORAS_DOMAIN, 542,-776);
    ROCKLOC(ZD_CIRCLE_ROCK_4, RCAREA_ZORAS_DOMAIN, SCENE_ZORAS_DOMAIN, 518,-832);
    ROCKLOC(ZD_CIRCLE_ROCK_5, RCAREA_ZORAS_DOMAIN, SCENE_ZORAS_DOMAIN, 462,-856);
    ROCKLOC(ZD_CIRCLE_ROCK_6, RCAREA_ZORAS_DOMAIN, SCENE_ZORAS_DOMAIN, 405,-832);
    ROCKLOC(ZD_CIRCLE_ROCK_7, RCAREA_ZORAS_DOMAIN, SCENE_ZORAS_DOMAIN, 382,-776);
    ROCKLOC(ZD_CIRCLE_ROCK_8, RCAREA_ZORAS_DOMAIN, SCENE_ZORAS_DOMAIN, 405,-719);
    ROCKLOC(ZF_BOULDER, RCAREA_ZORAS_FOUNTAIN, SCENE_ZORAS_FOUNTAIN, 189, 2586);
    ROCKLOC(ZF_SILVER_BOULDER, RCAREA_ZORAS_FOUNTAIN, SCENE_ZORAS_FOUNTAIN, 316, 2634);
    ROCKLOC(ZF_UNDERGROUND_BOULDER, RCAREA_ZORAS_FOUNTAIN, SCENE_ZORAS_FOUNTAIN, 317, 2631);
    ROCKLOC(ZR_BOULDER_1,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER, -1456, 434);
    ROCKLOC(ZR_BOULDER_2,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER, -1518, 435);
    ROCKLOC(ZR_BOULDER_3,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER, -1576, 430);
    ROCKLOC(ZR_BOULDER_4,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER, -1400, 482);
    ROCKLOC(ZR_CIRCLE_ROCK_1,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,-1635, -53);
    ROCKLOC(ZR_CIRCLE_ROCK_2,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,-1578, -76);
    ROCKLOC(ZR_CIRCLE_ROCK_3,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,-1555, -133);
    ROCKLOC(ZR_CIRCLE_ROCK_4,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,-1578, -189);
    ROCKLOC(ZR_CIRCLE_ROCK_5,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,-1635, -213);
    ROCKLOC(ZR_CIRCLE_ROCK_6,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,-1691, -189);
    ROCKLOC(ZR_CIRCLE_ROCK_7,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,-1715, -133);
    ROCKLOC(ZR_CIRCLE_ROCK_8,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,-1691, -76);
    ROCKLOC(ZR_UPPER_CIRCLE_BOULDER,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER, 672, -366);
    ROCKLOC(ZR_UPPER_CIRCLE_ROCK_1,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,668, -290);
    ROCKLOC(ZR_UPPER_CIRCLE_ROCK_2,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,724, -313);
    ROCKLOC(ZR_UPPER_CIRCLE_ROCK_3,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,748, -370);
    ROCKLOC(ZR_UPPER_CIRCLE_ROCK_4,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,724, -426);
    ROCKLOC(ZR_UPPER_CIRCLE_ROCK_5,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,668, -450);
    ROCKLOC(ZR_UPPER_CIRCLE_ROCK_6,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,611, -426);
    ROCKLOC(ZR_UPPER_CIRCLE_ROCK_7,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,588, -370);
    ROCKLOC(ZR_UPPER_CIRCLE_ROCK_8,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,611, -313);
    ROCKLOC(ZR_ROCK,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,2044, -786);
    ROCKLOC(ZR_UNDERWATER_ROCK_1,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,2425, -446);
    ROCKLOC(ZR_UNDERWATER_ROCK_2,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,2425, -524);
    ROCKLOC(ZR_UNDERWATER_ROCK_3,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,2503, -571);
    ROCKLOC(ZR_UNDERWATER_ROCK_4,RCAREA_ZORAS_RIVER,SCENE_ZORAS_RIVER,2550, -415);

    // 5 rocks by dc
    ROCKLOC(DMT_ROCK_1,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1816,-513);
    ROCKLOC(DMT_ROCK_2,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1831,-614);
    ROCKLOC(DMT_ROCK_3,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1857,-536);
    ROCKLOC(DMT_ROCK_4,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1878,-465);
    ROCKLOC(DMT_ROCK_5,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1787,-550);
    //child only
    ROCKLOC(DMT_SUMMIT_ROCK,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-327,-4286);
    // ring in front of gc
    ROCKLOC(DMT_CIRCLE_ROCK_1,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-383,-1126);
    ROCKLOC(DMT_CIRCLE_ROCK_2,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-326,-1149);
    ROCKLOC(DMT_CIRCLE_ROCK_3,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-303,-1206);
    ROCKLOC(DMT_CIRCLE_ROCK_4,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-326,-1262);
    ROCKLOC(DMT_CIRCLE_ROCK_5,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-383,-1286);
    ROCKLOC(DMT_CIRCLE_ROCK_6,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-439,-1262);
    ROCKLOC(DMT_CIRCLE_ROCK_7,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-463,-1206);
    ROCKLOC(DMT_CIRCLE_ROCK_8,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-439,-1149);
    ROCKLOC(DMT_BOULDER_1,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-625,-55);
    ROCKLOC(DMT_BOULDER_2,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-808,-59);
    ROCKLOC(DMT_BOULDER_3,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1060,-51);
    ROCKLOC(DMT_COW_BOULDER,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-688,-285);
    ROCKLOC(DMT_BRONZE_BOULDER_1,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1175,-803);
    ROCKLOC(DMT_BRONZE_BOULDER_2,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1948,1706);
    ROCKLOC(DMT_BRONZE_BOULDER_3,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-2019,1101);
    ROCKLOC(DMT_BRONZE_BOULDER_4,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1658,-88);
    ROCKLOC(DMT_BRONZE_BOULDER_5,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1753,445);
    ROCKLOC(DMT_BRONZE_BOULDER_6,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1018,1283);
    ROCKLOC(DMT_BRONZE_BOULDER_7,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1986,727);
    ROCKLOC(DMT_BRONZE_BOULDER_8,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-23,-3196);
    ROCKLOC(DMT_BRONZE_BOULDER_9,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-343,-2794);
    ROCKLOC(DMT_BRONZE_BOULDER_10,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-154,-2484);
    ROCKLOC(DMT_BRONZE_BOULDER_11,RCAREA_DEATH_MOUNTAIN_TRAIL,SCENE_DEATH_MOUNTAIN_TRAIL,-1590,-402);
    ROCKLOC(GC_LW_BOULDER_1, RCAREA_GORON_CITY, SCENE_GORON_CITY, 416, 1049);
    ROCKLOC(GC_LW_BOULDER_2, RCAREA_GORON_CITY, SCENE_GORON_CITY, 470, 1031);
    ROCKLOC(GC_LW_BOULDER_3, RCAREA_GORON_CITY, SCENE_GORON_CITY, 367, 1078);
    ROCKLOC(GC_ENTRANCE_BOULDER_1, RCAREA_GORON_CITY, SCENE_GORON_CITY, -670, 470);
    ROCKLOC(GC_ENTRANCE_BOULDER_2, RCAREA_GORON_CITY, SCENE_GORON_CITY, -607, 419);
    ROCKLOC(GC_ENTRANCE_BOULDER_3, RCAREA_GORON_CITY, SCENE_GORON_CITY, -756, 474);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_1,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1479, -794);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_2,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1478, -855);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_3,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1474, -624);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_4,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1471, -993);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_5,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1467, -1064);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_6,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1460, -1121);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_7,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1451, -567);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_8,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1448, -672);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_9,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1440, -1174);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_10,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1437, -1342);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_11,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1424, -1245);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_12,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1424, -609);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_13,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1399, -1300);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_14,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1394, -654);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_15,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1343, -698);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_16,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1319, -1086);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_17,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1312, -1039);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_18,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1306, -837);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_19,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1279, -656);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_20,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1255, -840);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_21,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1246, -1075);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_22,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1244, -589);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_23,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1210, -852);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_24,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1206, -627);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_25,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1187, -896);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_26,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1157, -954);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_27,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1130, -1137);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_28,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1120, -1001);
    ROCKLOC(GC_MAZE_SILVER_BOULDER_29,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1179, -1098);
    ROCKLOC(GC_MAZE_BOULDER_1,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1342, -628);
    ROCKLOC(GC_MAZE_BOULDER_2,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1456, -501);
    ROCKLOC(GC_MAZE_BOULDER_3,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1233, -511);
    ROCKLOC(GC_MAZE_BOULDER_4,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1137, -657);
    ROCKLOC(GC_MAZE_BOULDER_5,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1124, -913);
    ROCKLOC(GC_MAZE_BOULDER_6,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1326, -771);
    ROCKLOC(GC_MAZE_BOULDER_7,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1469, -737);
    ROCKLOC(GC_MAZE_BOULDER_8,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1476, -921);
    ROCKLOC(GC_MAZE_BOULDER_9,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1391, -1087);
    ROCKLOC(GC_MAZE_BOULDER_10,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1222, -997);
    ROCKLOC(GC_MAZE_BRONZE_BOULDER_1,RCAREA_GORON_CITY,SCENE_GORON_CITY,1541, -631);
    ROCKLOC(GC_MAZE_BRONZE_BOULDER_2,RCAREA_GORON_CITY,SCENE_GORON_CITY,1536, -861);
    ROCKLOC(GC_MAZE_BRONZE_BOULDER_3,RCAREA_GORON_CITY,SCENE_GORON_CITY,1536, -1102);
    ROCKLOC(GC_MAZE_BRONZE_BOULDER_4,RCAREA_GORON_CITY,SCENE_GORON_CITY,1534, -752);
    ROCKLOC(GC_MAZE_BRONZE_BOULDER_5,RCAREA_GORON_CITY,SCENE_GORON_CITY,1536, -991);
    ROCKLOC(GC_MAZE_ROCK,RCAREA_GORON_CITY,SCENE_GORON_CITY,-1197, -1329);
    ROCKLOC(COLOSSUS_SILVER_BOULDER, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS, 61, -1301);
    ROCKLOC(COLOSSUS_ROCK, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,1537, 667);
    ROCKLOC(COLOSSUS_CIRCLE_1_ROCK_1, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-250, -1272);
    ROCKLOC(COLOSSUS_CIRCLE_1_ROCK_2, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-193, -1295);
    ROCKLOC(COLOSSUS_CIRCLE_1_ROCK_3, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-170, -1352);
    ROCKLOC(COLOSSUS_CIRCLE_1_ROCK_4, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-193, -1408);
    ROCKLOC(COLOSSUS_CIRCLE_1_ROCK_5, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-250, -1432);
    ROCKLOC(COLOSSUS_CIRCLE_1_ROCK_6, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-306, -1408);
    ROCKLOC(COLOSSUS_CIRCLE_1_ROCK_7, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-330, -1352);
    ROCKLOC(COLOSSUS_CIRCLE_1_ROCK_8, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-306, -1295);
    ROCKLOC(COLOSSUS_CIRCLE_2_ROCK_1, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-834, -766 );
    ROCKLOC(COLOSSUS_CIRCLE_2_ROCK_2, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-777, -789 );
    ROCKLOC(COLOSSUS_CIRCLE_2_ROCK_3, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-754, -846 );
    ROCKLOC(COLOSSUS_CIRCLE_2_ROCK_4, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-777, -902 );
    ROCKLOC(COLOSSUS_CIRCLE_2_ROCK_5, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-834, -926 );
    ROCKLOC(COLOSSUS_CIRCLE_2_ROCK_6, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-890, -902 );
    ROCKLOC(COLOSSUS_CIRCLE_2_ROCK_7, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-914, -846 );
    ROCKLOC(COLOSSUS_CIRCLE_2_ROCK_8, RCAREA_DESERT_COLOSSUS, SCENE_DESERT_COLOSSUS,-890, -789 );
    ROCKLOC(HC_STORMS_GROTTO_ROCK_1, RCAREA_HYRULE_CASTLE, SCENE_GROTTOS,1811, 813);
    ROCKLOC(HC_STORMS_GROTTO_ROCK_2, RCAREA_HYRULE_CASTLE, SCENE_GROTTOS,1867, 789);
    ROCKLOC(HC_STORMS_GROTTO_ROCK_3, RCAREA_HYRULE_CASTLE, SCENE_GROTTOS,1891, 733);
    ROCKLOC(HC_STORMS_GROTTO_ROCK_4, RCAREA_HYRULE_CASTLE, SCENE_GROTTOS,1867, 676);
    ROCKLOC(HC_STORMS_GROTTO_ROCK_5, RCAREA_HYRULE_CASTLE, SCENE_GROTTOS,1811, 653);
    ROCKLOC(HC_STORMS_GROTTO_ROCK_6, RCAREA_HYRULE_CASTLE, SCENE_GROTTOS,1754, 676);
    ROCKLOC(HC_STORMS_GROTTO_ROCK_7, RCAREA_HYRULE_CASTLE, SCENE_GROTTOS,1731, 733);
    ROCKLOC(HC_STORMS_GROTTO_ROCK_8, RCAREA_HYRULE_CASTLE, SCENE_GROTTOS,1754, 789);
    locationTable[RC_BOTW_BOULDER_1] = Location::Rock(RC_BOTW_BOULDER_1, RCQUEST_VANILLA, RCAREA_BOTTOM_OF_THE_WELL, SCENE_BOTTOM_OF_THE_WELL, TWO_ACTOR_PARAMS(-683, -734), "BOTW Boulder 1", "BOTW Boulder 1",  RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_BOTW_BOULDER_1));
    locationTable[RC_BOTW_BOULDER_2] = Location::Rock(RC_BOTW_BOULDER_2, RCQUEST_VANILLA, RCAREA_BOTTOM_OF_THE_WELL, SCENE_BOTTOM_OF_THE_WELL, TWO_ACTOR_PARAMS(-632, -805), "BOTW Boulder 2", "BOTW Boulder 2",  RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_BOTW_BOULDER_2));
    locationTable[RC_BOTW_BOULDER_3] = Location::Rock(RC_BOTW_BOULDER_3, RCQUEST_VANILLA, RCAREA_BOTTOM_OF_THE_WELL, SCENE_BOTTOM_OF_THE_WELL, TWO_ACTOR_PARAMS(333,  -681), "BOTW Boulder 3", "BOTW Boulder 3",  RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_BOTW_BOULDER_3));
    locationTable[RC_BOTW_BOULDER_4] = Location::Rock(RC_BOTW_BOULDER_4, RCQUEST_VANILLA, RCAREA_BOTTOM_OF_THE_WELL, SCENE_BOTTOM_OF_THE_WELL, TWO_ACTOR_PARAMS(409,  -637), "BOTW Boulder 4", "BOTW Boulder 4",  RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_BOTW_BOULDER_4));
    locationTable[RC_BOTW_BOULDER_5] = Location::Rock(RC_BOTW_BOULDER_5, RCQUEST_VANILLA, RCAREA_BOTTOM_OF_THE_WELL, SCENE_BOTTOM_OF_THE_WELL, TWO_ACTOR_PARAMS(334,    -8), "BOTW Boulder 5", "BOTW Boulder 5",  RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_BOTW_BOULDER_5));
    locationTable[RC_BOTW_BOULDER_6] = Location::Rock(RC_BOTW_BOULDER_6, RCQUEST_VANILLA, RCAREA_BOTTOM_OF_THE_WELL, SCENE_BOTTOM_OF_THE_WELL, TWO_ACTOR_PARAMS(312,    64), "BOTW Boulder 6", "BOTW Boulder 6",  RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_BOTW_BOULDER_6));
#define MQROCK(id, area, x, z) (locationTable[RC_##id] = Location::Rock(RC_##id, RCQUEST_MQ, RCAREA_##area, SCENE_##area, TWO_ACTOR_PARAMS(x, z), #id, #id, RHT_POT_GERUDO_TRAINING_GROUND,    RG_RECOVERY_HEART,       SpoilerCollectionCheck::RandomizerInf(RAND_INF_##id)))
    MQROCK(DEKU_TREE_MQ_BOULDER_1, DEKU_TREE, -1237, 1558);
    MQROCK(DEKU_TREE_MQ_BOULDER_2, DEKU_TREE, -1183, 1522);
    MQROCK(DEKU_TREE_MQ_BOULDER_3, DEKU_TREE, -1129, 1469);
}

static RegisterShipInitFunc initFunc2(Rando::StaticData::RegisterRockLocations);